analysis:
  conditional_interaction:
    enable_chi_square_test: true
    significance_level: 0.05
    top_k_pairs: 10
  enable_combination_diversity_score: true
  enable_conditional_interaction_analysis: true
  enable_frequent_triples: true
  enable_gap_deviation_score: true
  enable_gap_stats: true
  enable_micro_bias_analysis: true
  enable_overlap_time_gap_analysis: true
  enable_pair_centrality: true
  enable_pair_graph_weights: true
  enable_pair_roi_score: true
  enable_pattern_interval: true
  enable_position_bias_analysis: true
  enable_position_frequency: true
  enable_position_number_stats: true
  enable_recent_gap: true
  enable_roi_pattern_groups: true
  enable_roi_trend_by_pattern: true
  enable_segment_10: true
  enable_segment_5: true
  enable_segment_history: true
  enable_segment_trend_history: true
  micro_bias:
    bias_threshold: 0.05
    enable_trend_analysis: true
    moving_average_window: 50
  overlap_time_gaps:
    analysis_window: 100
    enable_periodicity_detection: true
    min_overlap_count: 3
  paths:
    cache_dir: data/cache
    result_dir: data/result/analysis
  position_bias:
    enable_gap_analysis: true
    enable_position_statistics: true
    enable_ratio_analysis: true
  save_to:
    json: false
    npy: true
    txt: false
caching:
  cache_log_level: INFO
  cache_metrics:
    file_path: logs/cache_stats.json
    report_interval: 1000
    save: true
  enable_feature_cache: true
  max_cache_size: 10000
  vector_cache:
    clean_on_startup: false
    enabled: true
clustering:
  auto_adjust_clusters: true
  dbscan:
    eps: 0.5
    min_samples: 3
  max_clusters: 8
  min_clusters: 2
  min_silhouette_score: 0.3
  n_clusters: 5
  use_dbscan: false
data:
  cache_size: 1073741824
  historical_data_path: data/raw/lottery.csv
  max_number: 45
  min_number: 1
  sequence_length: 6
  test_size: 0.2
  validation_size: 0.1

lottery:
  ticket_price: 1000  # 로또 티켓 가격 (원)
  prize_structure:
    6: 2000000000  # 1등 평균 당첨금 (20억원)
    5: 1000000     # 2등 평균 당첨금 (100만원)  
    4: 50000       # 3등 평균 당첨금 (5만원)
    3: 5000        # 4등 평균 당첨금 (5천원)
execution:
  debug_mode: false
  default_mode: 1
  max_threads: 8
  parallel_execution: true
  probability_threshold: 0.6
  use_gpu: true
  vector_cache_size: 1000
  verbose: true
filtering:
  remove_low_variance_features: true
  variance_threshold: 0.01
filters:
  allow_duplicates: false
  exclude_exact_past_match: true
  max_consecutive: 5
  max_even_numbers: 4
  max_low_numbers: 4
  max_sum: 210
  min_even_numbers: 2
  min_low_numbers: 2
  min_sum: 90
frequency_weights:
  long_term: 0.6
  mid_term: 0.25
  short_term: 0.15
generation:
  enable_inverse_sampling: true
  enable_model_guided_generation: true
  enable_roi_guided_generation: true
  enable_structured_generation: true
  jaccard_diversity_threshold: 0.5
  min_cluster_diversity: 3
  model_ratio: 0.3
  pure_random_ratio: 0.1
  roi_data_path: data/roi/high_roi_combinations.json
  roi_ratio: 0.3
  structured_ratio: 0.3
models:
  feature_importance_threshold: 0.01
  gnn:
    batch_size: 64
    epochs: 200
    hidden_size: 256
    learning_rate: 0.0005
  lgbm_params:
    bagging_fraction: 0.8
    bagging_freq: 5
    boosting_type: gbdt
    feature_fraction: 0.9
    learning_rate: 0.03
    metric: auc
    n_estimators: 300
    num_leaves: 64
    objective: binary
    verbose: -1
  lstm:
    batch_size: 32
    epochs: 150
    hidden_size: 128
    learning_rate: 0.001
  prediction_threshold: 0.5
  rl:
    batch_size: 32
    epochs: 100
    hidden_size: 128
    learning_rate: 0.001
  save_feature_importance: true
  statistical:
    frequency_weight: 0.5
    pair_weight: 0.2
    recency_weight: 0.3
  use_probability: true
  validation_size: 0.2
  xgb_params:
    colsample_bytree: 0.8
    eval_metric: auc
    gamma: 0
    learning_rate: 0.05
    max_depth: 6
    min_child_weight: 1
    n_estimators: 100
    objective: binary:logistic
    reg_alpha: 0.1
    reg_lambda: 1.0
    subsample: 0.8
    use_label_encoder: false
    verbose: 0
new_pattern_analysis:
  conditional_interaction:
    enable_attraction_analysis: true
    enable_chi_square_test: true
    enable_repulsion_analysis: true
    enabled: true
    min_occurrence_threshold: 5
    significance_level: 0.05
    top_k_pairs: 10
  micro_bias:
    bias_threshold: 0.05
    change_rate_range: 0.5
    enable_segment_analysis: true
    enable_trend_analysis: true
    enabled: true
    moving_average_window: 50
    theoretical_odd_ratio: 0.5
  overlap_time_gaps:
    analysis_window: 100
    enable_periodicity_detection: true
    enabled: true
    gap_normalization_factor: 100
    max_recent_count_3: 10
    max_recent_count_4: 5
    min_overlap_count: 3
    stddev_normalization_factor: 50
  position_bias:
    enable_gap_analysis: true
    enable_position_statistics: true
    enable_ratio_analysis: true
    enabled: true
    min_max_normalization: true
    position_count: 6
new_vectorization:
  conditional_interaction_dims: 3
  micro_bias_dims: 4
  normalization:
    conditional_interaction: clip
    micro_bias: custom
    overlap_time_gaps: minmax
    position_bias: minmax
  overlap_time_gaps_dims: 5
  position_bias_dims: 5
  save_combined_vector: true
  save_individual_vectors: true
normalization:
  anomaly_filter:
    enabled: true
    method: zscore
    z_threshold: 2.5
  fallback:
    identical_scores: 0.5
    zero_std: 1e-8
  feature_vector: zscore
  model_score: minmax
number_ranges:
- - 1
  - 10
- - 11
  - 20
- - 21
  - 30
- - 31
  - 40
- - 41
  - 45
paths:
  analysis_result_dir: data/result/analysis
  cache_dir: data/cache
  data_dir: data
  feature_vector_path: data/cache/feature_vector_full.npy
  log_dir: logs
  model_save_dir: savedModels
  name_file_path: data/cache/feature_vector_full.names.json
  performance_report_dir: data/result/performance_reports
  processed_data_dir: data/processed
  raw_data_dir: data/raw
  result_dir: data/result
pattern:
  max_even_numbers: 4
  max_low_numbers: 4
  min_even_numbers: 2
  min_low_numbers: 2
  percentile_threshold: 0.95
pattern_features:
  include:
  - odd_even_ratio
  - total_sum
  - max_consecutive
  - cluster_score
  - recent_hit_score
  - range_density
  - pairwise_distance
  - hot_cold_mix_score
  - pair_centrality_avg
  - pair_roi_avg
  - position_number_variance
  - combination_diversity_score
  - gap_stddev
  - roi_group_score
  - frequent_triplet_flag
  - graph_connectivity_score
  - outlier_flag
  thresholds:
    percentile_threshold: 0.95
    risk_score_threshold: 0.65
    trend_score_threshold: 0.75
performance:
  batch_size: 512
  cache_hit_target: 0.9
  cuda_memory_fraction: 0.8
  gpu_device: cuda:0
  max_threads: 8
  parallel_execution: false
  prefetch_buffer_size: 4
  threading_backend: threading
  torch_amp_enabled: true
periods:
  mid_term: 0.025
  short_term: 0.012
recommendation:
  candidate_cluster_method: agglomerative
  clustering_diversity: true
  enable_jaccard_filter: true
  jaccard_threshold: 0.5
  model_weights:
    autoencoder: 0.15
    gnn: 0.2
    lstm: 0.1
    rl: 0.25
    statistical: 0.2
    unsupervised: 0.15
  use_adjusted_score: true
  use_models:
    autoencoder: true
    gnn: true
    lstm: true
    rl: true
    statistical: true
    unsupervised: true
reporting:
  enable_performance_report: true
  performance_metrics:
    accuracy: true
    f1: true
    precision: true
    recall: true
    roi: true
  report_dir: logs/reports
  report_path: data/result/performance_reports/data_analysis_performance_report.json
  save_formats:
    csv: true
    json: true
    txt: false
roi_weighting:
  enable: true
  # low_risk_bonus: 보너스 관련 설정 제거됨
  max_pairs: 2
  min_cluster_pairs: 2
  min_pairs: 1
  premium_pairs_boost: 0.2
  premium_pairs_count: 20
training:
  batch_size: 512
  early_stopping: true
  epochs: 100
  learning_rate: 0.001
  optimizer: adam
  patience: 10
  scheduler: cosine
  use_amp: true
  use_filtered_vector: true
  validation_split: 0.2
validation:
  essential_features:
  - gap_stddev
  - pair_centrality
  - hot_cold_mix_score
  - segment_entropy
  - roi_group_score
  - duplicate_flag
  - max_overlap_with_past
  - combination_recency_score
  - position_entropy_1
  - position_entropy_2
  - position_entropy_3
  - position_entropy_4
  - position_entropy_5
  - position_entropy_6
  - position_std_1
  - position_std_2
  - position_std_3
  - position_std_4
  - position_std_5
  - position_std_6
  - position_variance_avg
  - position_bias_score
  fail_on_dimension_mismatch: true
  fail_on_missing_features: true
  validate_vectors: true
vector:
  min_required_dimension: 70
vector_blueprint:
  groups:
    centrality_consecutive: 12
    cluster_features: 10
    distribution_pattern: 10
    gap_reappearance: 8
    overlap_patterns: 20
    pair_graph_vector: 20
    pattern_analysis: 25
    physical_structure: 11
    roi_features: 15
    segment_frequency: 15
  total_expected_dims: 95
  validation:
    auto_fix_dimensions: true
    enforce_dimensions: true
    min_entropy_score: 0.1
    nan_inf_threshold: 0.01
vectorizer:
  cache_threshold: 1000
  feature_vector_full:
    dimension_types:
    - statistical
    - pattern_based
    - centrality
    - roi_based
    - position_based
    min_dimensions: 20
    names_path: data/cache/feature_vector_full.names.json
    normalization: minmax
    output_path: data/cache/feature_vectors_full.npy
  normalize_output: true
  use_cache: true
  remove_low_variance: false
weights:
  long_term: 0.6
  mid_term: 0.23
  short_term: 0.17
