# 최적화 시스템 설정 파일

# ProcessPool 관리자 설정
process_pool:
  max_workers: 4
  chunk_size: 100
  timeout: 300

# 메모리 관리 설정
memory:
  max_memory_usage: 0.85
  cache_size: 268435456  # 256MB
  auto_cleanup_interval: 60.0

# 하이브리드 최적화 설정
hybrid:
  auto_optimization: true
  memory_threshold: 0.8
  cpu_threshold: 75.0
